// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PipefittersSupply.Infrastructure;

namespace PipefittersSupply.Migrations
{
    [DbContext(typeof(PipefittersSupplyDbContext))]
    [Migration("20210602044414_GettingCloser")]
    partial class GettingCloser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PipefittersSupply.Domain.Financing.CashDisbursement.CashDisbursementType", b =>
                {
                    b.Property<int>("CashDisbursementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CashDisbursementTypeId");

                    b.ToTable("CashDisbursementTypes", "Financing");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.Employees.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees", "HumanResources");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.Employees.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.TimeCards.TimeCard", b =>
                {
                    b.Property<int>("TimeCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("TimeCardId");

                    b.ToTable("TimeCards", "HumanResources");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PurchaseOrderId");

                    b.ToTable("PurchaseOrders", "Purchasing");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PurchaseOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PurchaseOrderId1")
                        .HasColumnType("int");

                    b.HasKey("PurchaseOrderDetailId");

                    b.HasIndex("PurchaseOrderId1");

                    b.ToTable("PurchaseOrderDetails", "Purchasing");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.Financing.CashDisbursement.CashDisbursementType", b =>
                {
                    b.OwnsOne("PipefittersSupply.Domain.Common.CreatedDate", "CreatedDate", b1 =>
                        {
                            b1.Property<int>("CashDisbursementTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("CreatedDate")
                                .HasDefaultValueSql("sysdatetime()");

                            b1.HasKey("CashDisbursementTypeId");

                            b1.ToTable("CashDisbursementTypes");

                            b1.WithOwner()
                                .HasForeignKey("CashDisbursementTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.LastModifiedDate", "LastModifiedDate", b1 =>
                        {
                            b1.Property<int>("CashDisbursementTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("LastModifiedDate");

                            b1.HasKey("CashDisbursementTypeId");

                            b1.ToTable("CashDisbursementTypes");

                            b1.WithOwner()
                                .HasForeignKey("CashDisbursementTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Financing.CashDisbursement.CashDisbursementTypeId", "Id", b1 =>
                        {
                            b1.Property<int>("CashDisbursementTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("CashDisbursementTypeId");

                            b1.ToTable("CashDisbursementTypes");

                            b1.WithOwner()
                                .HasForeignKey("CashDisbursementTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Financing.CashDisbursement.EventTypeName", "EventTypeName", b1 =>
                        {
                            b1.Property<int>("CashDisbursementTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("EventTypeName");

                            b1.HasKey("CashDisbursementTypeId");

                            b1.ToTable("CashDisbursementTypes");

                            b1.WithOwner()
                                .HasForeignKey("CashDisbursementTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Financing.CashDisbursement.PayeeTypeName", "PayeeTypeName", b1 =>
                        {
                            b1.Property<int>("CashDisbursementTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("PayeeTypeName");

                            b1.HasKey("CashDisbursementTypeId");

                            b1.ToTable("CashDisbursementTypes");

                            b1.WithOwner()
                                .HasForeignKey("CashDisbursementTypeId");
                        });

                    b.Navigation("CreatedDate");

                    b.Navigation("EventTypeName");

                    b.Navigation("Id");

                    b.Navigation("LastModifiedDate");

                    b.Navigation("PayeeTypeName");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.Employees.Employee", b =>
                {
                    b.HasOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeType", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.OwnsOne("PipefittersSupply.Domain.Common.AddressLine1", "AddressLine1", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("AddressLine1");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.AddressLine2", "AddressLine2", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("AddressLine2");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.City", "City", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("City");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.CreatedDate", "CreatedDate", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("CreatedDate")
                                .HasDefaultValueSql("sysdatetime()");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.IsActive", "IsActive", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("Value")
                                .HasColumnType("bit")
                                .HasColumnName("IsActive");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.LastModifiedDate", "LastModifiedDate", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("LastModifiedDate");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.MaritalStatus", "MaritalStatus", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nchar(1)")
                                .HasColumnName("MaritalStatus");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.StateProvinceCode", "State", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nchar(2)")
                                .HasColumnName("StateProvinceCode");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.Telephone", "Telephone", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("Telephone");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.Zipcode", "Zipcode", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("Zipcode");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeFirstName", "FirstName", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("FirstName");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeId", "Id", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("SupervisorId");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeLastName", "LastName", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("LastName");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeMiddleInitial", "MiddleInitial", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nchar(1)")
                                .HasColumnName("MiddleInitial");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeePayRate", "PayRate", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PayRate");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeSSN", "SSN", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("SSN");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeStartDate", "StartDate", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .HasColumnType("date")
                                .HasColumnName("StartDate");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeTypeIdentifier", "EmployeeType", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("EmployeeType");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.TaxExemption", "Exemptions", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("TaxExemptions");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("AddressLine1");

                    b.Navigation("AddressLine2");

                    b.Navigation("City");

                    b.Navigation("CreatedDate");

                    b.Navigation("EmployeeType");

                    b.Navigation("Exemptions");

                    b.Navigation("FirstName");

                    b.Navigation("Id");

                    b.Navigation("IsActive");

                    b.Navigation("LastModifiedDate");

                    b.Navigation("LastName");

                    b.Navigation("MaritalStatus");

                    b.Navigation("MiddleInitial");

                    b.Navigation("PayRate");

                    b.Navigation("SSN");

                    b.Navigation("StartDate");

                    b.Navigation("State");

                    b.Navigation("SupervisorId");

                    b.Navigation("Telephone");

                    b.Navigation("Zipcode");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.Employees.EmployeeType", b =>
                {
                    b.OwnsOne("PipefittersSupply.Domain.Common.CreatedDate", "CreatedDate", b1 =>
                        {
                            b1.Property<int>("EmployeeTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("CreatedDate")
                                .HasDefaultValueSql("sysdatetime()");

                            b1.HasKey("EmployeeTypeId");

                            b1.ToTable("EmployeeTypes");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.LastModifiedDate", "LastModifiedDate", b1 =>
                        {
                            b1.Property<int>("EmployeeTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("LastModifiedDate");

                            b1.HasKey("EmployeeTypeId");

                            b1.ToTable("EmployeeTypes");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeTypeIdentifier", "Id", b1 =>
                        {
                            b1.Property<int>("EmployeeTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EmployeeTypeId");

                            b1.ToTable("EmployeeTypes");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeTypeId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeTypeName", "EmployeeTypeName", b1 =>
                        {
                            b1.Property<int>("EmployeeTypeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("EmployeeTypeName");

                            b1.HasKey("EmployeeTypeId");

                            b1.ToTable("EmployeeTypes");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeTypeId");
                        });

                    b.Navigation("CreatedDate");

                    b.Navigation("EmployeeTypeName");

                    b.Navigation("Id");

                    b.Navigation("LastModifiedDate");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.TimeCards.TimeCard", b =>
                {
                    b.OwnsOne("PipefittersSupply.Domain.Common.CreatedDate", "CreatedDate", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.LastModifiedDate", "LastModifiedDate", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeId", "EmployeeId", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.TimeCards.OvertimeHours", "OvertimeHours", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.TimeCards.PayPeriodEndDate", "PayPeriodEnded", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.TimeCards.RegularHours", "RegularHours", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.TimeCards.TimeCardId", "Id", b1 =>
                        {
                            b1.Property<int>("TimeCardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("TimeCardId");

                            b1.ToTable("TimeCards");

                            b1.WithOwner()
                                .HasForeignKey("TimeCardId");
                        });

                    b.Navigation("CreatedDate");

                    b.Navigation("EmployeeId");

                    b.Navigation("Id");

                    b.Navigation("LastModifiedDate");

                    b.Navigation("OvertimeHours");

                    b.Navigation("PayPeriodEnded");

                    b.Navigation("RegularHours");

                    b.Navigation("SupervisorId");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrder", b =>
                {
                    b.OwnsOne("PipefittersSupply.Domain.Common.CreatedDate", "CreatedDate", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.LastModifiedDate", "LastModifiedDate", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.HumanResources.Employees.EmployeeId", "EmployeeId", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.ExpectedDeliveryDate", "ExpectedDeliveryDate", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderAmount", "PurchaseOrderAmount", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderDate", "PurchaseOrderDate", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderId", "Id", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.Vendor.VendorId", "VendorId", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("CreatedDate");

                    b.Navigation("EmployeeId");

                    b.Navigation("ExpectedDeliveryDate");

                    b.Navigation("Id");

                    b.Navigation("LastModifiedDate");

                    b.Navigation("PurchaseOrderAmount");

                    b.Navigation("PurchaseOrderDate");

                    b.Navigation("VendorId");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrder", null)
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId1");

                    b.OwnsOne("PipefittersSupply.Domain.Common.CreatedDate", "CreatedDate", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.LastModifiedDate", "LastModifiedDate", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.Quantity", "QuantityOrdered", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Common.UnitCost", "UnitCost", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.Inventory.InventoryId", "InventoryId", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderDetailId", "Id", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrderId", "PurchaseOrderId", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.OwnsOne("PipefittersSupply.Domain.Purchasing.PurchaseOrder.VendorPartNumber", "VendorPartNumber", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("PurchaseOrderDetailId");

                            b1.ToTable("PurchaseOrderDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderDetailId");
                        });

                    b.Navigation("CreatedDate");

                    b.Navigation("Id");

                    b.Navigation("InventoryId");

                    b.Navigation("LastModifiedDate");

                    b.Navigation("PurchaseOrderId");

                    b.Navigation("QuantityOrdered");

                    b.Navigation("UnitCost");

                    b.Navigation("VendorPartNumber");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.HumanResources.Employees.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PipefittersSupply.Domain.Purchasing.PurchaseOrder.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
